name: Muni
main: com.teamglokk.muni.Muni
version: 0.1.ALPHA
authors: [BobbShields]
commands:
    town:
        description: Town administration commands
        aliases: []
        usage: /town [params]
permissions:
    muni.*:
        description: Gives access to all Muni permissions
        children:
            muni.admin: true
            muni.mayor: true
            muni.deputy: true
            muni.town: true
    muni.admin:
        description: Gives access to all abilities with no costs
        default: false
    muni.mayor:
        description: Grants access to mayor and deputy commands.  Required to start a town
        default: true
        children:
            muni.deputy: true
            muni.town: true
            muni.mayor.remove: true
    muni.mayor.remove:
        description: The ability to delete the mayor's town
        default: false
    muni.deputy:
        description: Grants access to deputy commands
        default: false
        children:
            muni.town: true
            muni.deputy.changetax: true    
    muni.deputy.changetax:
        description: This allows the deputies to change tax rates
        default: false
    muni.town:
        description: Gives access to town commands
        default: true