name: Muni
main: com.teamglokk.muni.Muni
version: Alpha 0.1
authors: [BobbShields]
commands:
    town:
        description: Town creation, taxes, and info
        aliases: []
        usage: /town help
    mayor:
        description: For mayors to administer their towns
        aliases: []
        usage: /mayor help
    deputy:
        description: So deputies may work with towns
        aliases: []
        usage: /deputy help
    townadmin:
        description: For server staff, overrides cost and some checks
        aliases: []
        usage: /townadmin help
permissions:
    muni.*:
        description: Gives access to all Muni permissions
        children:
            muni.admin: true
            muni.mayor: true
            muni.deputy: true
            muni.town: true
    muni.admin:
        description: Gives access to all abilities with no costs
        default: false
    muni.mayor:
        description: Grants access to mayor and deputy commands.  Required to start a town
        default: true
        children:
            muni.deputy: true
            muni.town: true
            muni.mayor.remove: true
    muni.mayor.remove:
        description: The ability to delete the mayor's town
        default: false
    muni.deputy:
        description: Grants access to deputy commands
        default: false
        children:
            muni.town: true
            muni.deputy.changetax: true    
    muni.deputy.changetax:
        description: This allows the deputies to change tax rates
        default: false    
    muni.deputy.pushborder:
        description: This allows the deputies to change tax rates
        default: false
    muni.town:
        description: Gives access to town commands
        default: true